
name: Text Classification Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: 🛎 Checkout Repository
      uses: actions/checkout@v3

    - name:  Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Preprocess Data
      run: python utils/textclassification_preprocess.py

    - name: Train the Model
      run: python training/train_classification.py

    - name: Run Unit Tests
      run: python testing/textclassification_test.py

    - name: Check Model Performance
      run: python monitoring/textclassification_performance.py
  # Text Similarity Pipeline
    - name: Preprocess Data (Text Similarity)
      run: python utils/textsimilarity_preprocess.py

    - name: Run Similarity Evaluation
      run: python monitoring/different_textsimilarity_model_performance.py

    - name: Run Unit Tests (Text Similarity)
      run: python testing/textsimilarity_test.py

  deploy:
    needs: build-and-train
    runs-on: ubuntu-latest

    steps:
    - name: 🛎 Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name:  Deploy FastAPI Server
      run: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
